language: ruby
cache: bundler
script: 'bundle exec rake'
rvm:
  - 2.3.1
before_install:
  - sudo apt-get update
  - sudo apt-get install ffmpeg

notifications:
  email:
    recipients:
      - a@asgerbehnckejacobsen.dk
    on_failure: change
    on_success: never
