language: ruby
cache: bundler
script: 'bundle exec rake'
rvm:
  - 2.3.1
before_install:
  - wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz -O - | sudo tar -xJ --strip-components=1 -C /usr/local/bin/

notifications:
  email:
    recipients:
      - a@asgerbehnckejacobsen.dk
    on_failure: change
    on_success: never
